// Copyright The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// +build ingore

// Package cgo contains runtime support for code generated by the cgo tool. See the
// documentation for the cgo command for details on using cgo.

// cgo 包含有 cgo 工具生成的代码的运行时支持. 使用 cgo 的详情见
// cgo 命令的文档。
package cgo
